# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            JohnnySun
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://johnnysun.github.io
baseurl:          '/'
site.baseurl:     '/'

author:
  name:           'Johnny Suun'
  url:            https://twitter.com/bmy001

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/johnnysun
