# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            JohnnySun
tagline:          'Blog'
description:      'Android Developer @Mafengwo Inc.'
url:              http://johnnysun.github.io
baseurl:          /


author:
  name:           'Johnny Suun'
  url:            https://twitter.com/bmy001

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/johnnysun
